// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxqjrolvq4D-uoY2zb5h2c2cwC-RKclo',
    appId: '1:97560274388:web:0acb297e05d535213b2241',
    messagingSenderId: '97560274388',
    projectId: 'cloud-messaging-52e99',
    authDomain: 'cloud-messaging-52e99.firebaseapp.com',
    storageBucket: 'cloud-messaging-52e99.firebasestorage.app',
    measurementId: 'G-VJX29NP0X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLgYWIvGAHxm3mV6UDYVhXUlypwsFOZZ0',
    appId: '1:97560274388:android:00febfaab17e6c4d3b2241',
    messagingSenderId: '97560274388',
    projectId: 'cloud-messaging-52e99',
    storageBucket: 'cloud-messaging-52e99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzS-MIhgIwPiDtMg-uyKbdh8nNsLCDk8',
    appId: '1:97560274388:ios:00b92a606974e17a3b2241',
    messagingSenderId: '97560274388',
    projectId: 'cloud-messaging-52e99',
    storageBucket: 'cloud-messaging-52e99.firebasestorage.app',
    iosBundleId: 'com.example.messageboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQzS-MIhgIwPiDtMg-uyKbdh8nNsLCDk8',
    appId: '1:97560274388:ios:00b92a606974e17a3b2241',
    messagingSenderId: '97560274388',
    projectId: 'cloud-messaging-52e99',
    storageBucket: 'cloud-messaging-52e99.firebasestorage.app',
    iosBundleId: 'com.example.messageboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxqjrolvq4D-uoY2zb5h2c2cwC-RKclo',
    appId: '1:97560274388:web:0acb297e05d535213b2241',
    messagingSenderId: '97560274388',
    projectId: 'cloud-messaging-52e99',
    authDomain: 'cloud-messaging-52e99.firebaseapp.com',
    storageBucket: 'cloud-messaging-52e99.firebasestorage.app',
    measurementId: 'G-VJX29NP0X4',
  );
}
